# Questions per group
Q: [
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε τη βιτρίνα με τα είδη γυναικείου καλλωπισμού. Από τι ήταν φτιαγμένοι οι αρχαίοι καθρέφτες;',
    'Από τι ήταν φτιαγμένες οι αρχαίες χτένες;',
    'Από τι ήταν φτιαγμένα τα αρχαία δοχεία αρωμάτων;',
    'Τι περιείχε η αρχαία κρέμα για μακιγιάζ;',
    'Ποια είδη κοσμημάτων βλέπετε στη βιτρίνα 23;'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε τη βιτρίνα με τα είδη ένδυσης. Παρατηρήστε τα πήλινα αγαλματίδια. Ποιες πληροφορίες μάς δίνουν για τα ρούχα των αρχαίων Ελλήνων;',
    'Πόσα υφαντικά βάρη μπορείτε να βρείτε μέσα στη βιτρίνα 19;',
    'Από τι υλικό είναι φτιαγμένα τα υφαντικά βάρη;',
    'Πού χρησίμευαν τα υφαντικά βάρη;',
    'Πόσες βελόνες βλέπετε στη βιτρίνα 19;'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε τη βιτρίνα με τα είδη σπιτιού και γευμάτων. Τι είδους έπιπλα βλέπετε εδώ;',
    'Ξέρετε σε τι χρησιμεύουν τα λυχνάρια;',
    'Βρείτε και συγκρίνετε τα λυχνάρια που υπάρχουν στις προθήκες 17 και 24. Σε τι διαφέρουν μεταξύ τους;',
    'Βρείτε κοντά στην προθήκη 24 το ανάγλυφο που σας δείχνω. Τι απεικονίζει;',
    'Πώς ονομάζεται το έπιπλο στο οποίο είναι μισοξαπλωμένοι οι άνδρες στο ανάγλυφο;'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε τη βιτρίνα με τα παιχνίδια. Θα σας δείχνω εικόνες με σημερινά παιχνίδια και θα μου λέτε αν υπάρχουν εδώ παρόμοια αρχαία παιχνίδια. Υπάρχει εδώ παρόμοιο παιχνίδι;',
    'Υπάρχει εδώ παρόμοιο παιχνίδι;',
    'Υπάρχει εδώ παρόμοιο παιχνίδι;',
    'Υπάρχει εδώ παρόμοιο παιχνίδι;',
    'Υπάρχει εδώ παρόμοιο παιχνίδι;',
    'Σε τι νομίζετε ότι διαφέρουν περισσότερο τα αρχαία από τα σύγχρονα παιχνίδια;'
  ]
]

# Choices per question per group
C: [
  [
    ['Ελεφαντόδοντο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Κόκκαλο', 'Ατσάλι', 'Χαλκό', 'Ελεφαντόδοντο', 'Ξύλο', 'Μάρμαρο'],
    ['Γυαλί', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Αλάβαστρο', 'Λευκό του σιδήρου', 'Λευκό του μολύβδου'],
    ['Περιδέραια', 'Σκουλαρίκια', 'Ρολόγια', 'Βραχιόλια', 'Στέμματα', 'Δαχτυλίδια', 'Καρφίτσες'],
  ],
  [
    ['Είχαν χρώματα', 'Δεν είχαν χρώματα', 'Στερεώνονταν με πόρπες και περόνες', 'Περιλάμβαναν και παντελόνια'],
    ['8', '12', '16', '20'],
    ['Από σίδερο', 'Από χαλκό', 'Από πηλό', 'Από χρυσό'],
    ['Για να μένουν σταθερές οι οριζόντιες κλωστές του αργαλειού', 'Για να μένουν σταθερές οι κάθετες κλωστές του αργαλειού', 'Για να ευθυγραμμίζεται το ύφασμα', 'Για να κάνει κρόσσια το ύφασμα'],
    ['0', '1', '2', '4']
  ],
  [
    ['Τραπέζια', 'Καρέκλες', 'Καναπέδες', 'Πολυθρόνες'],
    ['Για να πλενόμαστε', 'Για να κάνουμε ευχές', 'Για να βάζουμε λάδι στο φαγητό', 'Για να φωτίζουν'],
    ['Στο μέγεθος', 'Στο υλικό', 'Στη διακόσμηση'],
    ['Άνδρες σε συμπόσιο', 'Μαθητές σε σχολείο', 'Τρεις θεούς του Ολύμπου'],
    ['Κρεβάτι', 'Τάβλα', 'Ανάκλιντρο', 'Καναπές'],
  ],
  [
    ['Ναι', 'Όχι'],
    ['Ναι', 'Όχι'],
    ['Ναι', 'Όχι'],
    ['Ναι', 'Όχι'],
    ['Ναι', 'Όχι'],
    ['Φτιάχνονταν από άλλα υλικά', 'Δεν έχουν διαφορές', 'Ήταν χειροποίητα', 'Παίζονταν από πιο μικρά παιδιά']
  ],
]

# Correct answers (zero-based indexing)
A: [
  [2,[0,3,4],[0,3],2,[0,1,3,5,6]],
  [[0,2],2,2,1,3],
  [[0,1],3,1,0,2],
  [0,0,0,1,1,[0,2]]
]


# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing)
I: [
  ['00.png', '01.png', '02.png','03.png',''],
  ['','','','',''],
  ['','', '','23.png',''],
  ['30.png','31.png','32.png','33.png','34.png','']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing)
V: [
  ['00.mp3', '01.mp3', '02.mp3', '03.mp3', '04.mp3'],
  ['10.mp3', '11.mp3', '12.mp3', '13.mp3', '14.mp3'],
  ['20.mp3', '21.mp3', '22.mp3', '23.mp3', '24.mp3'],
  ['30.mp3', '31.mp3', '32.mp3', '33.mp3', '34.mp3', '35.mp3']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game b
# amth_games
start_pose: [5.38, 18.75, 0,0,0, -0.91, 0.42]

# amth_offices_wunknown for testing (museum is crowded)
#start_pose: [7.13205432033, 10.5253486524, 0,0,0, 0.315150221271, 0.94904179994]
