# Questions per group
Q: [
  ['G1 Q1', 'G1 Q2'],
  ['G2 Q1', 'G2 Q2'],
  ['G3 Q1', 'G3 Q2', 'G3 Q3'],
  ['G4 Q1']
]

# Choices per question per group
C: [
  [
    ['G1 Q1 C1', 'G1 Q1 C2', 'G1 Q1 C3', 'G1 Q1 C4'],
    ['G1 Q2 C1', 'G1 Q2 C2', 'G1 Q2 C3', 'G1 Q2 C4']
  ],
  [
    ['G2 Q1 C1', 'G2 Q1 C2', 'G2 Q1 C3', 'G2 Q1 C4'],
    ['G2 Q2 C1', 'G2 Q2 C2', 'G2 Q2 C3', 'G2 Q2 C4']
  ],
  [
    ['G3 Q1 C1', 'G3 Q1 C2', 'G3 Q1 C3', 'G3 Q1 C4'],
    ['G3 Q2 C1', 'G3 Q2 C2', 'G3 Q2 C3', 'G3 Q2 C4'],
    ['G3 Q3 C1', 'G3 Q3 C2', 'G3 Q3 C3', 'G3 Q3 C4']
  ],
  [
    ['G4 Q1 C1', 'G4 Q1 C2']
  ]
]

# Correct answers (zero-based indexing)
A: [
  [0,'E2003412DC03011924274797'],
  ['E2003412DC03011924274797',3],
  ['E2003412DC03011924274797',3,0],
  [1]
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'
