## signifies a line break

# Questions per group
Q: [
  [
    'Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα σύνεργα γραφής. Παρατηρήστε προσεκτικά τα αντικείμενα της προθήκης. Ποιό από αυτά που βρίσκονται στην προθήκη βλέπετε να υπάρχει στην εικόνα που σας δείχνω?',
    'Στην προθήκη 3 υπάρχουν δύο τμήματα μικρών αγγείων στα οποία έγραψαν κάποιοι μαθητές της αρχαιότητας. Μπορείτε να τα εντοπίσετε? Από τι υλικό είναι φτιαγμένα?',
    'Σε σχέση με τα σύγχρονα γράμματα τι παρατηρείτε?',
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε τις λίθινες στήλες. Τι παρατηρείτε σχετικά με τα γράμματα?'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε την προθήκη με τα αντικείμενα που χρησιμοποιούσαν οι αθλητές. Πόσα μικρά αγγεία βλέπετε?',
    'Πώς ονομάζονται τα αγγεία?',
    'Ποιά ήταν η χρήση τους?',
    'Στην προθήκη 4 θα βρείτε μερικές κάρτες. Μόνο μία κάρτα αντιστοιχεί στη σωστή απάντηση. Η ερώτηση είναι: ποιό αντικείμενο χρησιμοποιούσαν οι αθλητές για να καθαρίσουν το σώμα τους από τη σκόνη? Οταν βρείτε την απάντηση φέρτε την κάρτα κοντά στην καρδιά μου και πατήστε το κουμπί της ερώτησης',
    'Πόσα τέτοια ολόκληρα αντικείμενα μπορείτε να δείτε μέσα στην προθήκη? Προσοχή! Είπα ΟΛΟΚΛΗΡΑ',
    'Τώρα θέλω να χρησιμοποιήσετε τον βοηθό μου και να βρείτε το τμήμα αγγείου το οποίο δόθηκε ως έπαθλο σε αγώνες. Πρόκειται για ένα μεγάλο ή ένα μικρό αγγείο?',
    'Μπορείτε να διαβάσετε το όνομα του αθλητή που το κέρδισε?',
    'Στην Αρχαία Μακεδονία τοποθετούσαν ένα ανάγλυφο, φανταστείτε μια εικόνα σκαλισμένη στην πέτρα, πάνω στον τάφο ενός νεκρού. Αυτό ονομάζεται επιτύμβιο ανάγλυφο. Παρατηρήστε το επιτύμβιο ανάγλυφο που βρίσκεται δίπλα στον προθήκη. Ποιά έπαθλα απεικονίζονται?',
    'Στη σημερινή εποχή ποιά έπαθλα κερδίζουν οι νικητές στους αγώνες?'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε την προθήκη με το αρχαίο αγγείο που απεικονίζει την αναχώρηση του πολεμιστή. Κοντά του στέκεται ο πατέρας του, ένας νεαρός δούλος, η γυναίκα του κι ένας άλλος πολεμιστής. Παρατηρήστε προσεκτικά τον πολεμιστή που εικονίζεται στο κέντρο της εικόνας. Ποια από τα όπλα ή τα τμήματά τους, που φορά ή κρατά, βρίσκονται στην προθήκη?',
    'Στην προθήκη υπάρχουν κράνη δύο τύπων. Παρατηρήστε τα προσεκτικά. Το κράνος Χαλκιδικού τύπου προστάτευε μόνο την μύτη. Σωστό ή Λάθος?',
    'Το κράνος Ιλλυρικού τύπου δεν είχε προστασία της μύτης αλλά προστάτευε τα αυτιά. Σωστό ή Λάθος?',
    'Ο κάθε στρατιώτης φρόντιζε για τον οπλισμό του. Με τι διακοσμούσαν οι αρχαίοι Έλληνες τις ασπίδες τους και τα κράνη τους?'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε την προθήκη με τα σύνεργα της γεωργίας και της αλιείας. Πόσα αγκίστρια, βελόνες, και βαρίδια βλέπετε?',
    'Γιατί πιστεύετε ότι τα εργαλεία στην προθήκη δεν σώθηκαν ακέραια?',
    'Στα δεξιά της προθήκης εικονίζονται παραστάσεις από αγγεία. Μπορείτε να τις εντοπίσετε? Τι απεικονίζουν?',
    'Μπορείτε να εντοπίσετε την κυψέλη που βρίσκεται μέσα στην αίθουσα? Μοιάζει με τις σημερινές κυψέλες?',
    'Ποιές ήταν οι χρήσεις του λαδιού στην Αρχαία Ελλάδα?'
  ]
]

# Choices per question per group
C: [
  [
    ['Μολύβι', 'Γραφίδα', 'Χαρτί', 'Στυλό'],
    ['Χρυσό', 'Πέτρα', 'Ασήμι', 'Πηλό'],
    ['Κάποια γράμματα είναι όμοια με τα σύγχρονα, κάποια άλλα όχι', 'Δε μοιάζουν καθόλου με τα σύγχρονα', 'Όλα είναι ίδια με τα σύγχρονα'],
    ['Είναι μικρά και σε κανονικά διαστήματα μεταξύ τους', 'Είναι κεφαλαία και σε κανονικά διαστήματα μεταξύ τους', 'Είναι κεφαλαία και κολλημένα το ένα με το άλλο']
  ],
  [
    ['1', '2', '3', '4'],
    ['Αγγειάκια', 'Δοχειάκια', 'Κανατάκια', 'Αρύβαλλοι'],
    ['Να πίνουν κρασί οι αθλητές μετά τον αγώνα', 'Να πίνουν γάλα οι αθλητές πριν τον αγώνα','Να μεταφέρουν το λάδι που θα χρησιμοποιούσαν οι αθλητές για να αλείψουν το σώμα τους'],
    ['Σπάτουλα', 'Σφουγγάρι','Στλεγγίδα'],
    ['1', '2', '3', '4'],
    ['Μικρό', 'Μεγάλο'],
    ['Αριστομένης','Αριστόβουλος','Θρασύβουλος','Αριστείδης'],
    ['Κλαδί φοινικιάς', 'Μετάλλια', 'Κύπελλο', 'Στεφάνι', 'Αμφορέας', 'Χρήματα'],
    ['Κλαδί φοινικιάς', 'Μετάλλια', 'Κύπελλο', 'Στεφάνι', 'Αμφορέας', 'Χρήματα']
  ],
  [
    ['Ασπίδα', 'Κράνος', 'Σπαθί', 'Τουφέκι'],
    ['Σωστό', 'Λάθος'],
    ['Σωστό', 'Λάθος'],
    ['Σκηνές ψαρέματος', 'Τον Ήλιο της Μακεδονίας', 'Κρανία', 'Αγαπημένα τους πρόσωπα']
  ],
  [
    ['6 Αγκίστρια, 2 Βελόνες, 3 Βαρίδια', '7 Αγκίστρια, 3 Βελόνες, 3 Βαρίδια', '8 Αγκίστρια, 2 Βελόνες, 2 Βαρίδια', '8 Αγκίστρια, 3 Βελόνες, 3 Βαρίδια'],
    ['Γιατί ο χρόνος είναι αδυσώπητος', 'Γιατί τα ξύλινα μέρη καταστράφηκαν', 'Γιατί έσπασαν κατά την ανασκαφή'],
    ['Μάζεμα ελαιών', 'Σκηνή ψαρέματος', 'Σκηνή μαγειρέματος', 'Μάζεμα σταφυλιών', 'Πάτημα σταφυλιών', 'Σκηνή κυνηγιού'],
    ['Ναι είναι ίδια', 'Έχει το ίδιο σχήμα αλλά είναι από διαφορετικό υλικό', 'Όχι, δεν έχει ούτε το ίδιο σχήμα ούτε είναι από το ίδιο υλικό'],
    ['Στο φαγητό', 'Στον αθλητισμό για προθέρμανση', 'Στη θυσία', 'Στους αγώνες ως έπαθλο']
  ]
]

# Correct answers (zero-based indexing). As many answers as questions, as many
# group answers as group questions
A: [
  [1,3,0,1],
  [1,3,2,'E280689400005002B9626D1B',2,1,1,[0,3,4],[1,2,3,5]],
  [[0,1],1,0,1],
  [3,1,[0,1,3,5],2,[0,1,3]]
]

# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing). As many images as questions, as many
# group images as group questions

I: [
  ['00.png', '', '',''],
  ['', '','','','','','','',''],
  ['20.png','','',''],
  ['','','','','']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing). As many audiofiles as questions, as many
# group audiofiles as group questions
V: [
  ['00.mp3', '01.mp3', '02.mp3', '03.mp3'],
  ['10.mp3', '11.mp3', '12.mp3', '13.mp3', '14.mp3', '15.mp3', '16.mp3', '17.mp3', '18.mp3'],
  ['20.mp3', '21.mp3', '22.mp3', '23.mp3'],
  ['30.mp3', '31.mp3', '32.mp3', '33.mp3', '34.mp3']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game a
# amth_games
#start_pose: [10.4758667738, 34.9752528641, 0,0,0, 0.994354572594, 0.106108359528]

# amth_offices_wunknown for testing (museum is crowded)
start_pose: [11.7774129583, 14.1673720608, 0, 0, 0, -0.951217617272, 0.30852073608]
