# Questions per group
Q: [
  ['GB G1 Q1', 'GB G1 Q2'],
  ['GB G2 Q1', 'GB G2 Q2'],
  ['GB G3 Q1', 'GB G3 Q2', 'GB G3 Q3'],
  ['GB G4 Q1']
]

# Choices per question per group
C: [
  [
    ['GB G1 Q1 C1', 'GB G1 Q1 C2', 'GB G1 Q1 C3', 'GB G1 Q1 C4'],
    ['GB G1 Q2 C1', 'GB G1 Q2 C2', 'GB G1 Q2 C3', 'GB G1 Q2 C4']
  ],
  [
    ['GB G2 Q1 C1', 'GB G2 Q1 C2', 'GB G2 Q1 C3', 'GB G2 Q1 C4'],
    ['GB G2 Q2 C1', 'GB G2 Q2 C2', 'GB G2 Q2 C3', 'GB G2 Q2 C4']
  ],
  [
    ['GB G3 Q1 C1', 'GB G3 Q1 C2', 'GB G3 Q1 C3', 'GB G3 Q1 C4'],
    ['GB G3 Q2 C1', 'GB G3 Q2 C2', 'GB G3 Q2 C3', 'GB G3 Q2 C4'],
    ['GB G3 Q3 C1', 'GB G3 Q3 C2', 'GB G3 Q3 C3', 'GB G3 Q3 C4']
  ],
  [
    ['GB G4 Q1 C1', 'GB G4 Q1 C2']
  ]
]

# Correct answers (zero-based indexing)
A: [
  [0,'E2003412DC03011924274797'],
  ['E2003412DC03011924274797',0],
  ['E2003412DC03011924274797',0,0],
  [0]
]


# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing)
I: [
  ['', '', '',''],
  ['', ''],
  ['', '', ''],
  ['']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing)
V: [
  ['', '', '',''],
  ['', ''],
  ['', '', ''],
  ['']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game a
start_pose: [11.844532775, 5.68836989903, 0,0,0, 0.973881896599, 0.227055172758]
#start_pose: [10.4179109403, 4.9571560998, 0,0,0, 0.33038906878, 0.94384483006]
