# Questions per group
Q: [
  [
    'Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα είδη γυναικείου καλλωπισμού. Θα σας δείχνω μία εικόνα της σημερινής εποχής και θα σας ρωτάω από τι υλικό ήταν φτιαγμένο το αντίστοιχο αρχαίο αντικείμενο',
    'Από τι ήταν φτιαγμένοι οι αρχαίοι καθρέπτες?',
    'Από τι ήταν φτιαγμένες οι αρχαίες χτένες?',
    'Από τι ήταν φτιαγμένα τα αρχαία τσιμπιδάκια?',
    'Από τι ήταν φτιαγμένα τα αρχαία δοχεία αρωματικών ουσιών?',
    'Από τι ήταν φτιαγμένη η αρχαία λευκή πούδρα?',
    'Ποιά είδη κοσμημάτων βλέπετε στην προθήκη 23? (Υπάρχουν πολλαπλές ορθές απαντήσεις. Μετά την επιλογή πατήστε το κουμπί της ερώτησης)',
    'Μπορείτε να εντοπίσετε τα τρία γυναικεία κεφάλια που βρίσκονται δίπλα από την προθήκη 23? Πώς θα περιγράφατε τα χτενίσματά τους?'
  ],
  [
    'Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα είδη ένδυσης. Πόσα υφαντικά βάρη μπορείτε να βρείτε μέσα στην προθήκη?',
    'Από τι υλικό είναι φτιαγμένα τα υφαντικά βάρη?',
    'Μπορείτε να σκεφτείτε και να περιγράψετε πού χρησίμευαν?',
    'Σε τι χρησίμευε ο αργαλειός?',
    'Πόσες βελόνες βλέπετε στην προθήκη 19?',
    'Από τι υλικό είναι φτιαγμένες οι βελόνες?',
    'Παρατηρήστε τα πήλινα αγαλματίδια της προθήκης 20. Ποιές πληροφορίες μάς δίνουν για τα ρούχα των αρχαίων Ελλήνων? (Υπάρχουν πολλαπλές ορθές απαντήσεις. Μετά την επιλογή πατήστε το κουμπί της ερώτησης)',
    'Ανάμεσα στα αντικείμενα στις προθήκες 20 και 23 υπάρχουν αντικείμενα με τα οποία οι αρχαίοι Έλληνες στερέωναν τα ρούχα τους. Πώς ονομάζεται αυτό που σας δείχνω σε αυτή την εικόνα?',
    'Πώς ονομάζεται αυτό που σας δείχνω σε αυτή την εικόνα?'
  ],
  [
    'Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα είδη σπιτιού και γευμάτων. Τι είδους έπιπλα βλέπετε στην προθήκη? (Υπάρχουν πολλαπλές ορθές απαντήσεις. Μετά την επιλογή πατήστε το κουμπί της ερώτησης)',
    'Τι συμπεραίνετε σε σχέση με το μέγεθός τους?',
    'Παρατηρήστε στην προθήκη 18 τα αγγεία. Μοιάζουν με σημερινά αντικείμενα?',
    'Ξέρετε σε τι χρησιμεύουν τα λυχνάρια?',
    'Βρείτε και συγκρίνετε τα λυχνάρια που υπάρχουν στις προθήκες 17 και 24. Σε τι διαφέρουν μεταξύ τους? (Υπάρχουν πολλαπλές ορθές απαντήσεις. Μετά την επιλογή πατήστε το κουμπί της ερώτησης)',
    'Βρειτε κοντά στην προθήκη 24 το ανάγλυφο που σας δείχνω. Τι απεικονίζει το ανάγλυφο?',
    'Πώς ονομάζεται το έπιπλο στο οποίο είναι μισοξαπλωμένοι οι άνδρες?'
  ],
  [
    'Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη που περιέχει την εικόνα που σας δείχνω. Μπορείτε να εντοπίσετε το παιχνίδι που κρατά το παιδί? ',
    'Από τι υλικό είναι φτιαγμένο το παιχνίδι?',
    'Παρατηρήστε στην προθήκη το ειδώλιο (μικρό αγαλματίδιο από πηλό) που εικονίζει τις δύο κοπέλες. Τι παιχνίδι νομίζετε ότι παίζουν?',
    'Θα σας δείχνω εικόνες με σημερινά παιχνίδια και θα μου λέτε αν υπάρχουν τα αντίστοιχα αρχαία στις προθήκες που βρήκατε',
    'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
    'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
    'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
    'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
    'Ανάμεσα στα παιχνίδια υπάρχουν και τρία που παράγουν ήχο. Μπορείτε να σκεφτείτε ποια είναι? (Υπάρχουν πολλαπλές ορθές απαντήσεις. Μετά την επιλογή πατήστε το κουμπί της ερώτησης)',
    'Σε τι νομίζετε ότι διαφέρουν περισσότερο τα αρχαία από τα σύγχρονα παιχνίδια?'
  ]
]

# Choices per question per group
C: [
  [
    ['Εντάξει'],
    ['Ελεφαντόδοντο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Κόκκαλο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Ελεφαντόδοντο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Γυαλί ή αλάβαστρο', 'Γυαλί ή ατσάλι', 'Αλάβαστρο ή χαλκό', 'Πηλό'],
    ['Αλάβαστρο', 'Ασβέστη', 'Λευκό του σιδήρου', 'Λευκό του μολύβδου'],
    ['Περιδέραια', 'Σκουλαρίκια', 'Ρολόγια', 'Βραχιόλια', 'Δαχτυλίδια', 'Καρφίτσες'],
    ['Είναι πολύ απλά', 'Είναι πολύ περίτεχνα', 'Άλλα είναι απλά και άλλα είναι περίτεχνα', 'Οι γυναίκες ήταν ατημέλητες']
  ],
  [
    ['8', '12', '16', '20'],
    ['Από σίδερο', 'Από χαλκό', 'Από πηλό', 'Από χρυσό'],
    ['Για να μένουν σταθερές οι οριζόντιες κλωστές', 'Για να μένουν σταθερές οι κάθετες κλωστές', 'Για να ευθυγραμμίζεται το ύφασμα', 'Για να κάνει κρόσσια το ύφασμα'],
    ['Για να ζεσταίνουν το φαγητό', 'Για να κόβουν ξύλα', 'Για να υφαίνουν τα ρούχα τους', 'Για θυσία στη θεά του ρουχισμού'],
    ['0', '1', '2', '4'],
    ['Μέταλλο', 'Κόκκαλο', 'Μέταλλο και κόκκαλο', 'Μέταλλο, κόκκαλο, και ελεφαντόδοντο'],
    ['Είχαν χρώματα', 'Δεν είχαν χρώματα', 'Δεν είχαν πολλές ραφές', 'Χρησιμοποιούσαν πόρπες και παραμάνες', 'Χρησιμοποιούσαν ζώνες'],
    ['Περόνη', 'Πόρπη', 'Στλεγγίδα', 'Αρυβαλλος'],
    ['Περόνη', 'Πόρπη', 'Στλεγγίδα', 'Αρυβαλλος'],
  ],
  [
    ['Τραπέζια', 'Καρέκλες', 'Καναπέδες', 'Πολυθρόνες'],
    ['Είναι αντίγραφα επίπλων σε μικρό μέγεθος', 'Είναι τα πρωτότυπα έπιπλα σε φυσικό μέγεθος'],
    ['Ναι', 'Όχι'],
    ['Για να πλενόμαστε', 'Για να κάνουμε ευχές', 'Στο φαγητό', 'Για να φωτίζουν'],
    ['Στο μέγεθος', 'Στο υλικό', 'Στη διακόσμηση'],
    ['Παράσταση συμποσίου (γιορτή για άνδρες)', 'Παράσταση συμποσίου (γιορτή για γυναίκες)', 'Τρεις θεούς του Ολύμπου', 'Παράσταση διάλεξης'],
    ['Κρεβάτι', 'Τάβλα', 'Ανάκλιντρο', 'Αρύβαλλος'],
  ],
  [
    ['Ναι, είναι κούκλα', 'Ναι, είναι μικρό ζωάκι', 'Ναι, είναι ένα μωρό', 'Όχι, δεν είναι δυνατόν'],
    ['Ασήμι', 'Ασβέστη', 'Μάρμαρο', 'Πηλό'],
    ['Καβάλες (μακριά γαϊδούρα)', 'Αρύβαλλο (μακριά γαϊδούρα)', 'Εσώμακτρο', 'Εξώμακτρο'],
    ['Εντάξει'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['Κουδουνίστρες', 'Κουδουνάκια', 'Ζάρια', 'Πλαγγόνα', 'Εννεάδα'],
    ['Φτιάχνονταν από άλλα υλικά', 'Τα φτιάχναν τα μέλη της οικογένειας', 'Δεν έχουν διαφορές','Παίζονταν από πιο μικρά παιδιά']
  ],
]

# Correct answers (zero-based indexing)
A: [
  [0,2,0,2,0,3, [0,1,3,4,5], 2],
  [2,2,1,2,3,2,[0,2,3,4],0,1],
  [[0,1],0,0,3,[0,1,2],0,2],
  [0,3,0,0,1,1,0,2, [0,1,2], 0]
]


# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing)
I: [
  ['00.png', '01.png', '02.png','03.png','04.png','05.png', '',''],
  ['', '','','','','','','17.png','18.png'],
  ['', '', '','','','25.png', ''],
  ['30.png','','','','34.png','35.png','36.png','37.png','','']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing)
V: [
  ['00.mp3', '01.mp3', '02.mp3', '03.mp3', '04.mp3', '05.mp3', '06.mp3', '07.mp3'],
  ['10.mp3', '11.mp3', '12.mp3', '13.mp3', '14.mp3', '15.mp3', '16.mp3', '17.mp3', '18.mp3'],
  ['20.mp3', '21.mp3', '22.mp3', '23.mp3', '24.mp3', '25.mp3', '26.mp3'],
  ['30.mp3', '31.mp3', '32.mp3', '33.mp3', '34.mp3', '35.mp3', '36.mp3', '37.mp3', '38.mp3', '39.mp3']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game b
# amth_games
start_pose: [5.38, 18.75, 0,0,0, -0.91, 0.42]

# amth_offices_wunknown for testing (museum is crowded)
#start_pose: [7.13205432033, 10.5253486524, 0,0,0, 0.315150221271, 0.94904179994]
