## signifies a line break

# Questions per group
Q: [
  ['Βρείτε την προθήκη 3 με τα σύνεργα της γραφής. Παρατηρήστε προσεκτικά τα αντικείμενα της προθήκης. Ποιό από αυτά που βρίσκονται στην προθήκη βλέπετε να υπάρχει στην εικόνα που σας δείχνω?',
  'Στην προθήκη 3 υπάρχουν δύο τμήματα μικρών αγγείων στα οποία έγραψαν κάποιοι μαθητές της αρχαιότητας. Μπορείτε να τα εντοπίσετε? Από τί υλικό είναι φτιαγμένα?',
  'Τί παρατηρείτε σε σχέση με τα σύγχρονα γράμματα?',
  'Κοιτάξτε τις λίθινες στήλες δίπλα και απέναντι από την προθήκη 3. Τί παρατηρείτε σχετικά με τα γράμματα?'],
  ['GA G2 Q1', 'GA G2 Q2'],
  ['GA G3 Q1', 'GA G3 Q2', 'GA G3 Q3'],
  ['GA G4 Q1']
]

# Choices per question per group
C: [
  [
    ['Μολύβι', 'Γραφίδα', 'Χαρτί', 'Στυλό'],
    ['Χρυσό', 'Πέτρα', 'Ασήμι', 'Πηλό'],
    ['Κάποια γράμματα είναι όμοια με τα σύγχρονα, κάποια άλλα όχι', 'Δε μοιάζουν καθόλου', 'Όλα είναι ίδια μεταξύ τους'],
    ['Είναι μικρά και σε κανονικά διαστήματα μεταξύ τους', 'Είναι κεφαλαία και κολλημένα το ένα με το άλλο', 'Είναι κεφαλαία και σε κανονικά διαστήματα μεταξύ τους']
  ],
  [
    ['GA G2 Q1 C1', 'GA G2 Q1 C2', 'GA G2 Q1 C3', 'GA G2 Q1 C4'],
    ['GA G2 Q2 C1', 'GA G2 Q2 C2', 'GA G2 Q2 C3', 'GA G2 Q2 C4']
  ],
  [
    ['GA G3 Q1 C1', 'GA G3 Q1 C2', 'GA G3 Q1 C3', 'GA G3 Q1 C4'],
    ['GA G3 Q2 C1', 'GA G3 Q2 C2', 'GA G3 Q2 C3', 'GA G3 Q2 C4'],
    ['GA G3 Q3 C1', 'GA G3 Q3 C2', 'GA G3 Q3 C3', 'GA G3 Q3 C4']
  ],
  [
    ['GA G4 Q1 C1', 'GA G4 Q1 C2']
  ]
]

# Correct answers (zero-based indexing)
A: [
  [1,3,0,2],
  ['E2003412DC03011924274797',0],
  ['E2003412DC03011924274797',0,0],
  [0]
]

# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing)
I: [
  ['00.png', '', '',''],
  ['', ''],
  ['', '', ''],
  ['']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing)
V: [
  ['00.mp3', '01.mp3', '02.mp3','03.pm3'],
  ['', ''],
  ['', '', ''],
  ['']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game a
start_pose: [11.7975408942, 5.96052106997, 0,0,0, -0.999693209985, 0.0247686477145]

# Goal pose at the end of game a
goal_pose: [11.7975408942, 5.96052106997, 0,0,0, -0.999693209985, 0.0247686477145]
