# Questions per group
Q: [
  ['Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα είδη γυναικείου καλλωπισμού. Θα σας δείχνω μία εικόνα της σημερινής εποχής και θα σας ρωτάω από τι υλικό ήταν φτιαγμένο το αντίστοιχο αρχαίο αντικείμενο',
  'Από τί ήταν φτιαγμένοι οι αρχαίοι καθρέπτες?',
  'Από τί ήταν φτιαγμένες οι αρχαίες χτένες?',
  'Από τί ήταν φτιαγμένα τα αρχαία τσιμπιδάκια?',
  'Από τί ήταν φτιαγμένα τα αρχαία δοχεία αρωματικών ουσιών?',
  'Από τί ήταν φτιαγμένο το αρχαίο μακιγιάζ?',
  'Τι είδους κοσμήματα βλέπετε στην προθήκη 23?',
  'Μπορείτε να εντοπίσετε τα τρία γυναικεία κεφάλια που βρίσκονται δίπλα από την προθήκη 23? Πώς θα περιγράφατε τα χτενίσματά τους?'
  ],
  ['Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα είδη ένδυσης. Πόσα υφαντικά βάρη μπορείτε να βρείτε μέσα στην προθήκη?',
  'Από τί υλικό είναι φτιαγμένα τα υφαντικά βάρη?',
  'Μπορείτε να σκεφτείτε και να περιγράψετε πού χρησίμευαν?',
  'Σε τί χρησίμευε ο αργαλειός?',
  'Πόσες βελόνες βλέπετε στην προθήκη 19?',
  'Από τί υλικό είναι φτιαγμένες οι βελόνες?',
  'Παρατηρήστε τα πήλινα αγαλματίδια της προθήκης 20. Ποιές πληροφορίες μάς δίνουν για τα ρούχα των αρχαίων Ελλήνων?',
  'Ανάμεσα στα αντικείμενα στις προθήκες 20 και 23 υπάρχουν αντικείμενα με τα οποία οι αρχαίοι Έλληνες στερέωναν τα ρούχα τους. Πώς ονομάζεται αυτό που σας δείχνω σε αυτή την εικόνα?',
  'Πώς ονομάζεται αυτό που σας δείχνω σε αυτή την εικόνα?'],
  ['Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα είδη σπιτιού και γευμάτων. Τί είδους έπιπλα βλέπετε στην προθήκη?',
  'Τι συμπεραίνετε σε σχέση με το μέγεθός τους?',
  'Παρατηρήστε στην προθήκη 18 τα αγγεία. Μοιάζουν με σημερινά αντικείμενα?',
  'Ξέρετε σε τί χρησιμεύουν τα λυχνάρια?',
  'Βρείτε και συγκρίνετε τα λυχνάρια που υπάρχουν στις προθήκες 17 και 24. Σε τί διαφέρουν μεταξύ τους?',
  'Βρείτε την προθήκη με το ανάγλυφο που σάς δείχνω. Τί απεικονίζει το ανάγλυφο?',
  'Πώς ονομάζεται το έπιπλο στο οποίο είναι ημιξαπλωμένοι οι άνδρες?',
  'Στην ίδια προθήκη βρίσκονται αγγεία από την εικόνα που σας δείχνω. Σε τί χρησίμευε η οινοχόη?',
  'Στην ίδια προθήκη βρίσκονται αγγεία από την εικόνα που σας δείχνω. Σε τί χρησίμευε ο κρατήρας?',
  'Στην ίδια προθήκη βρίσκονται αγγεία από την εικόνα που σας δείχνω. Σε τί χρησίμευε η κύλικα?'],
  ['Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη που περιέχει την εικόνα που σάς δείχνω. Μπορείτε να εντοπίσετε το παιχνίδι που κρατά το παιδί? ',
  'Από τι υλικό είναι φτιαγμένο το παιχνίδι?',
  'Παρατηρήστε στην προθήκη το ειδώλιο (μικρό αγαλματίδιο από πηλό) που εικονίζει τις δύο κοπέλες. Τι παιχνίδι νομίζετε ότι παίζουν?',
  'Θα σας δείχνω εικόνες με σημερινά παιχνίδια και θα μου λέτε αν υπάρχουν τα αντίστοιχα αρχαία στις προθήκες που βρήκατε',
  'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
  'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
  'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
  'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
  'Αυτό το παιχνίδι βρίσκεται στην προθήκη 17 ή στην προθήκη 21?',
  'Ανάμεσα στα παιχνίδια υπάρχουν και τρία που παράγουν ήχο. Μπορείτε να σκεφτείτε ποια είναι?',
  'Σε τι νομίζετε ότι διαφέρουν περισσότερο τα αρχαία από τα σύγχρονα παιχνίδια?'
  ]
]

# Choices per question per group
C: [
  [
    ['Εντάξει'],
    ['Ελεφαντόδοντο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Ελεφαντόδοντο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Ελεφαντόδοντο', 'Ατσάλι', 'Χαλκό', 'Πηλό'],
    ['Γυαλί και αλάβαστρο', 'Γυαλί και ατσάλι', 'Αλάβαστρο και χαλκό', 'Πηλό'],
    ['Αλάβαστρο', 'Ασβέστη', 'Λευκό του σιδήρου', 'Λευκό του μολύβδου'],
    ['Περιδέραια', 'Σκουλαρίκια', 'Ρολόγια', 'Βραχιόλια', 'Δαχτυλίδια', 'Καρφίτσες'],
    ['Είναι πολύ απλά', 'Είναι πολύ περίτεχνα', 'Άλλα είναι απλά και άλλα είναι περίτεχνα', 'Οι γυναίκες ήταν ατημέλητες']
  ],
  [
    ['8', '12', '16', '20'],
    ['Από σίδερο', 'Από χαλκό', 'Από πηλό', 'Από χρυσό'],
    ['Για να μένουν σταθερές οι οριζόντιες κλωστές', 'Για να μένουν σταθερές οι κάθετες κλωστές', 'Για να ευθυγραμμίζεται το ύφασμα', 'Για να κάνει κρόσσια το ύφασμα'],
    ['Για να ζεσταίνουν το φαγητό', 'Για να κόβουν ξύλα', 'Για να υφαίνουν τα ρούχα τους', 'Για θυσία στη θεά του ρουχισμού'],
    ['0', '1', '2', '4'],
    ['Μέταλλο', 'Οστό', 'Μέταλλο και οστό', 'Μέταλλο, οστό, και ελεφαντόδοντο'],
    ['Είχαν χρώματα', 'Δεν είχαν χρώματα', 'Δεν είχαν πολλές ραφές', 'Χρησιμοποιούσαν πόρπες και παραμάνες', 'Χρησιμοποιούσαν ζώνες'],
    ['Περόνη', 'Πόρπη', 'Στλεγγίδα', 'Αρυβαλλος'],
    ['Περόνη', 'Πόρπη', 'Στλεγγίδα', 'Αρυβαλλος'],
  ],
  [
    ['Τραπέζια', 'Καρέκλες', 'Καναπέδες', 'Πολυθρόνες'],
    ['Είναι αντίγραφα επίπλων σε μικρό μέγεθος', 'Είναι τα πρωτότυπα έπιπλα σε φυσικό μέγεθος'],
    ['Ναι', 'Όχι'],
    ['Για να πλενόμαστε', 'Για να κάνουμε ευχές', 'Στο φαγητό', 'Για να φωτίζουν'],
    ['Στο μέγεθος', 'Στο χρώμα', 'Στο υλικό', 'Στη διακόσμηση', 'Στην ηλικία'],
    ['Είναι μία παράσταση συμποσίου (γιορτή για άνδρες)', 'Ειναι μία παράσταση συμποσίου (γιορτή για γυναίκες)', 'Είναι τρεις Θεοί του Ολύμπου', 'Είναι μία παράσταση διάλεξης'],
    ['Κρεβάτι', 'Τάβλα', 'Ανάκλιντρο', 'Αρύβαλλος'],
    ['Ήταν κανάτα για να σερβίρουν το κρασί από τον κρατήρα σε κύλικες', 'Ήταν ειδικό αγγείο για το ανακατεμα του οίνου με το νερό', 'Ήταν ποτήρι για την κατανάλωση κρασιού στα συμπόσια', 'Ήταν δοχείο για δημητριακά'],
    ['Ήταν κανάτα για να σερβίρουν το κρασί από τον κρατήρα σε κύλικες', 'Ήταν ειδικό αγγείο για το ανακατεμα του οίνου με το νερό', 'Ήταν ποτήρι για την κατανάλωση κρασιού στα συμπόσια', 'Ήταν δοχείο για δημητριακά'],
    ['Ήταν κανάτα για να σερβίρουν το κρασί από τον κρατήρα σε κύλικες', 'Ήταν ειδικό αγγείο για το ανακατεμα του οίνου με το νερό', 'Ήταν ποτήρι για την κατανάλωση κρασιού στα συμπόσια', 'Ήταν δοχείο για δημητριακά']
  ],
  [
    ['Ναι, είναι κούκλα', 'Ναι, είναι μικρό ζωάκι', 'Ναι, είναι ένα μωρό', 'Όχι, δεν είναι δυνατόν'],
    ['Ασήμι', 'Ασβέστη', 'Μάρμαρο', 'Πηλό'],
    ['Καβάλες (μακριά γαϊδούρα)', 'Αρύβαλλο (μακριά γαϊδούρα)', 'Εσώμακτρο', 'Εξώμακτρο'],
    ['Εντάξει'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['17', '21', 'Σε καμία από τις δύο'],
    ['Κουδουνίστρες', 'Κουδουνάκια', 'Ζάρια', 'Πλαγγόνα', 'Εννεάδα'],
    ['Φτιάχνονταν από άλλα υλικά', 'Τα φτιάχναν τα μέλη της οικογένειας', 'Δεν έχουν διαφορές','Παίζονταν από πιο μικρά παιδιά']
  ],
]

# Correct answers (zero-based indexing)
A: [
  [0,2,0,2,0,3, [0,1,3,4,5], 2],
  [2,2,1,2,3,2,[0,2,3,4],0,1],
  [[0,1],0,0,3,[0,2,3],0,2,0,1,2],
  [0,3,0,0,1,1,0,1,2, [0,1,2], [0,1]]
]


# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing)
I: [
  ['00.png', '01.png', '02.png','03.png','04.png','05.png', '',''],
  ['', '','','','','','','17.png','18.png'],
  ['', '', '','','','25.png', '', '27.png','28.png','29.png'],
  ['30.png','','','','34.png','35.png','36.png','37.png','38.png','','']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing)
V: [
  ['00.mp3', '01.mp3', '02.mp3', '03.mp3', '04.mp3', '05.mp3', '06.mp3', '07.mp3'],
  ['10.mp3', '11.mp3', '12.mp3', '13.mp3', '14.mp3', '15.mp3', '16.mp3', '17.mp3', '18.mp3'],
  ['20.mp3', '21.mp3', '22.mp3', '23.mp3', '24.mp3', '25.mp3', '26.mp3', '27.mp3', '28.mp3', '29.mp3'],
  ['30.mp3', '31.mp3', '32.mp3', '33.mp3', '34.mp3', '35.mp3', '36.mp3', '37.mp3', '38.mp3', '39.mp3', '310.mp3']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game b
start_pose: [4.98766658505, 24.520899454, 0,0,0, -0.0797889896815, 0.996811776177]
