## qq signifies a line break

# Questions per group
Q: [
  ['Βρείτε την προθήκη 3 με τα σύνεργα της γραφής. qq Παρατηρήστε προσεκτικά τα αντικείμενα της προθήκης. qq Ποιό από αυτά που βρίσκονται στην προθήκη βλέπετε qq να υπάρχει στην εικόνα που σας δείχνω?', 'GA G1 Q2'],
  ['GA G2 Q1', 'GA G2 Q2'],
  ['GA G3 Q1', 'GA G3 Q2', 'GA G3 Q3'],
  ['GA G4 Q1']
]

# Choices per question per group
C: [
  [
    ['Μολύβι', 'Γραφίδα', 'Χαρτί', 'Στυλό'],
    ['GA G1 Q2 C1', 'GA G1 Q2 C2', 'GA G1 Q2 C3', 'GA G1 Q2 C4']
  ],
  [
    ['GA G2 Q1 C1', 'GA G2 Q1 C2', 'GA G2 Q1 C3', 'GA G2 Q1 C4'],
    ['GA G2 Q2 C1', 'GA G2 Q2 C2', 'GA G2 Q2 C3', 'GA G2 Q2 C4']
  ],
  [
    ['GA G3 Q1 C1', 'GA G3 Q1 C2', 'GA G3 Q1 C3', 'GA G3 Q1 C4'],
    ['GA G3 Q2 C1', 'GA G3 Q2 C2', 'GA G3 Q2 C3', 'GA G3 Q2 C4'],
    ['GA G3 Q3 C1', 'GA G3 Q3 C2', 'GA G3 Q3 C3', 'GA G3 Q3 C4']
  ],
  [
    ['GA G4 Q1 C1', 'GA G4 Q1 C2']
  ]
]

# Correct answers (zero-based indexing)
A: [
  [1,'E2003412DC03011924274797'],
  ['E2003412DC03011924274797',0],
  ['E2003412DC03011924274797',0,0],
  [0]
]

# Image to display alongside the Question
I: [
  ['0.png', ''],
  ['', ''],
  ['', '', ''],
  ['']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game a
start_pose: [11.7975408942, 5.96052106997, 0,0,0, -0.999693209985, 0.0247686477145]

# Goal pose at the end of game a
goal_pose: [11.7975408942, 5.96052106997, 0,0,0, -0.999693209985, 0.0247686477145]
