## signifies a line break

# Questions per group
Q: [
  [
    'Χρησιμοποιήστε το βοηθό μου και βρείτε την προθήκη με τα σύνεργα γραφής. Παρατηρήστε προσεκτικά τα αντικείμενα της προθήκης. Ποιό από αυτά που βρίσκονται στην προθήκη βλέπετε να υπάρχει στην εικόνα που σας δείχνω?',
    'Στην προθήκη 3 υπάρχουν δύο τμήματα μικρών αγγείων στα οποία έγραψαν κάποιοι μαθητές της αρχαιότητας. Σε σχέση με τα σύγχρονα γράμματα τι παρατηρείτε?',
    'Που είναι πιο πιθανό να συναντήσουμε τον Αριστοτέλη να κάνει μάθημα στον Μέγα Αλέξανδρο? Η απάντηση κρύβεται πάνω από τη λίθινη στήλη της φωτογραφίας.',
    'Η γραφή ήταν σημαντική στις αγοραπωλησίες. Ποια από τις παρακάτω είναι μια συνηθισμένη τιμή πώλησης σπιτιού στην Αρχαία Μακεδονία το 350 π.Χ.? Βρείτε την απάντηση κοντά στη στήλη της φωτογραφίας.'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε την προθήκη με τα αντικείμενα που χρησιμοποιούσαν οι αθλητές. Ποιά ήταν η χρήση τους?',
    'Ποιό αντικείμενο χρησιμοποιούσαν οι αθλητές για να καθαρίσουν το σώμα τους από τη σκόνη? Στην προθήκη 4 θα βρείτε μερικές κάρτες. Μόνο μία κάρτα αντιστοιχεί στη σωστή απάντηση. Φέρτε την κάρτα κοντά στην καρδιά μου και πατήστε το κουμπί της ερώτησης',
    'Τώρα θέλω να χρησιμοποιήσετε τον βοηθό μου και να βρείτε το τμήμα αγγείου το οποίο δόθηκε ως έπαθλο σε αγώνες. Μπορείτε να διαβάσετε το όνομα του αθλητή που το κέρδισε?',
    'Στην Αρχαία Μακεδονία τοποθετούσαν ένα ανάγλυφο, φανταστείτε μια εικόνα σκαλισμένη στην πέτρα, πάνω στον τάφο ενός νεκρού. Αυτό ονομάζεται επιτύμβιο ανάγλυφο. Παρατηρήστε το επιτύμβιο ανάγλυφο που βρίσκεται δίπλα στην προθήκη. Ποιά έπαθλα απεικονίζονται?'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε την προθήκη με τον οπλισμό των αρχαίων Μακεδόνων. Ποια είδη όπλων βλέπετε?',
    'Πως ονομάζεται το διάσημο όπλο της Μακεδονικής Φάλαγγας?',
    'Πώς έκαναν πιο θανατηφόρα τα ξίφη οι Μακεδόνες?',
    'Από τι υλικά ήταν φτιαγμένα τα όπλα?'
  ],
  [
    'Χρησιμοποιήστε τον βοηθό μου και βρείτε την προθήκη με τα σύνεργα της γεωργίας και της αλιείας. Πόσα αγκίστρια, βελόνες, και βαρίδια βλέπετε?',
    'Στα δεξιά της προθήκης εικονίζονται παραστάσεις από αγγεία. Μπορείτε να τις εντοπίσετε? Τι απεικονίζουν?',
    'Μπορείτε να εντοπίσετε την κυψέλη που βρίσκεται μέσα στην αίθουσα? Μοιάζει με τις σημερινές κυψέλες?',
    'Τι είναι το τρικλίνιο? Βρείτε την απάντηση κοντά στη φωτογραφία που βλέπετε.'
  ]
]

# Choices per question per group
C: [
  [
    ['Μολύβι', 'Γραφίδα', 'Χαρτί', 'Στυλό'],
    ['Κάποια γράμματα είναι όμοια με τα σύγχρονα, κάποια άλλα όχι', 'Δε μοιάζουν καθόλου με τα σύγχρονα', 'Όλα είναι ίδια με τα σύγχρονα'],
    ['Στο παλάτι του Φιλίππου', 'Στο σπίτι του Φιλίππου', 'Στην ύπαιθρο'],
    ['50 Δραχμές', '500 Δραχμές', '5000 Δραχμές']
  ],
  [
    ['Να πίνουν κρασί οι αθλητές μετά τον αγώνα', 'Να πίνουν γάλα οι αθλητές πριν τον αγώνα','Να μεταφέρουν το λάδι που θα χρησιμοποιούσαν οι αθλητές για να αλείψουν το σώμα τους'],
    ['Σπάτουλα', 'Σφουγγάρι','Στλεγγίδα'],
    ['Αριστομένης','Αριστόβουλος','Θρασύβουλος','Αριστείδης'],
    ['Κλαδί φοινικιάς', 'Μετάλλια', 'Κύπελλο', 'Στεφάνι', 'Αμφορέας', 'Χρήματα'],
  ],
  [
    ['Πιστόλι', 'Σπιρούνι','Παραγναθίδα','Κνημίδα'],
    ['Δόρυ', 'Φαλαγγίνα','Σάρισα','Σπιρούνι'],
    ['Με φωτιά', 'Με δηλητήριο','Κάνοντας τα πιο μακριά'],
    ['Χαλκό', 'Γύψο', 'Σίδηρο', 'Μάρμαρο','Άργυρο']
  ],
  [
    ['6 Αγκίστρια, 2 Βελόνες, 3 Βαρίδια', '7 Αγκίστρια, 3 Βελόνες, 3 Βαρίδια', '8 Αγκίστρια, 2 Βελόνες, 2 Βαρίδια', '8 Αγκίστρια, 3 Βελόνες, 3 Βαρίδια'],
    ['Μάζεμα ελαιών', 'Σκηνή ψαρέματος', 'Σκηνή μαγειρέματος', 'Μάζεμα σταφυλιών', 'Πάτημα σταφυλιών', 'Σκηνή κυνηγιού'],
    ['Ναι είναι ίδια', 'Έχει το ίδιο σχήμα αλλά είναι από διαφορετικό υλικό', 'Όχι, δεν έχει ούτε το ίδιο σχήμα ούτε είναι από το ίδιο υλικό'],
    ['Χώρος εστίασης', 'Χώρος φιλοξενίας', 'Αποθήκη με 3 χώρους']
  ]
]

# Correct answers (zero-based indexing). As many answers as questions, as many
# group answers as group questions
A: [
  [1,0,2,1],
  [2,'E280689400005002B9626D1B',1,[0,3,4]],
  [[1,2,3],2,1,[0,2,4]],
  [3,[0,1,3,5],2,0]
]

# Image to display alongside the Question
# The naming convention is AB.png, where A=group number, and B = question number
# (zero-based indexing). As many images as questions, as many
# group images as group questions

I: [
  ['00.png', '', '02.png','03.png'],
  ['', '','',''],
  ['20.png','','',''],
  ['','','','33.png']
]

# Speak the question
# The naming convention is AB.mp3, where A=group number, and B = question number
# (zero-based indexing). As many audiofiles as questions, as many
# group audiofiles as group questions
V: [
  ['00.mp3', '01.mp3', '02.mp3', '03.mp3'],
  ['10.mp3', '11.mp3', '12.mp3', '13.mp3'],
  ['20.mp3', '21.mp3', '22.mp3', '23.mp3'],
  ['30.mp3', '31.mp3', '32.mp3', '33.mp3']
]

# RFID measurements file
rfid_file: 'results_001625143965.txt'

# Starting pose for game a
# amth_games
start_pose: [10.4758667738, 34.9752528641, 0,0,0, 0.994354572594, 0.106108359528]

# amth_offices_wunknown for testing (museum is crowded)
#start_pose: [11.7774129583, 14.1673720608, 0, 0, 0, -0.951217617272, 0.30852073608]
